### PR TITLE
Integrate codecov.io

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by Henni** [comment]
A gitignore entry for the coverage data wouldn't hurt.
Otherwise :+1:

**Comment by DeepDiver1975** [comment]
@Henni tests are not yet running on travis and fail because chrome cannot be started .....

ideas are welcome :wink:

**Comment by DeepDiver1975** [comment]
https://karma-runner.github.io/0.8/plus/Travis-CI.html

**Comment by Henni** [comment]
@DeepDiver1975 we will be able to switch to PhantomJS after @irgendwie removed the dav lib.
The dav lib relies on ES6's `Set` which isn't supported by PhantomJS (https://kangax.github.io/compat-table/es6/#phantom)

**Comment by Henni** [comment]
A bit of research tells me that Firefox is preinstalled on travis machines. We could test in Firefox instead of Chrome.

But let's stick with Chrome if something like this works:

```
before_script:
    - 'export CHROME_BIN=chromium-browser'
    - 'export DISPLAY=:99.0'
    - 'sh -e /etc/init.d/xvfb start'
```

**Comment by Henni** [comment]
experimenting at #285

**Comment by Henni** [comment]
The [Chrome Version on Travis](https://travis-ci.org/owncloud/contacts/builds/118483071#L472) is 37!!! This version is from 2014-08-26!
Additionally the travis logs show a lot of warnings because it uses the node version 0.10 (latest stable: 5.9.1)

We might have to use a different travis setup and install node and chrome ourselves.

**Comment by DeepDiver1975** [comment]
Lets pull in underscore with Bower. Otherwise we would need to install a full ownCloud core

**Comment by Henni** [comment]
fixed :)

**Comment by DeepDiver1975** [comment]
Nice

**Pull request merged**
