### PR TITLE
Filter fields which are only allowed to be present once 

### LINKED ISSUE #89: Creation of multiple fields for Organization and Nickname possible
This should not be possible, right? Fields like organization and nickname should only exist once I assume?

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #89

### CODE REVIEW

**Comment by Henni** [comment]
Looks good so far, but can we maybe reduce the size of the `vCardMeta` object by defining a default value for `multiple`?
I believe most attributes can only be set once in vCards. Thus I would suggest to default to false and only define `multiple: true` in special cases.

**Comment by DeepDiver1975** [comment]
> Looks good so far, but can we maybe reduce the size of the vCardMeta object by defining a default value for multiple?
> I believe most attributes can only be set once in vCards. Thus I would suggest to default to false and only define multiple: true in special cases.

feel free to adjust the code in this pr :wink:

**Comment by Henni** [comment]
Small issue I found: adding a field which is only allowed once, leads to a blank select.
Instead it should again show "Add field".

**Comment by DeepDiver1975** [comment]
rebased

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
