### PR TITLE
Allow invalid urls

### PR DESCRIPTION
**Pull request by Henni**
fixes that urls aren't saved, if they don't match angular's url pattern.

### CODE REVIEW

**Comment by irgendwie** [comment]
Does **not** work for me :-1:

**Comment by Henni** [comment]
@irgendwie this might have been because #134 was missing.
Rebased and should work now

**Comment by irgendwie** [comment]
Seems so, works now as expected. :+1:

Still, if you add an URL not starting with http,
in the clickable arrow it is treated (now) as a relative path beginning from `index.php/apps/`.

As example:

> URL: asdf

leads to

> http://localhost/oc/index.php/apps/asdf

**Comment by Henni** [comment]
@irgendwie that's a different issue. (and probably not in scope for 1.0)

**Comment by irgendwie** [comment]
@Henni just wanted to address this issue, since it will be introduced with this PR.

**Pull request merged**
