### PR TITLE
Small fixes

### LINKED ISSUE #24: Show first contact by default
The content-detail view should always display a contact. On start, simply the first one in the list.

### LINKED ISSUE #72: »No contacts« placeholder should not show until everything is loaded
Currently the »No contacts« placeholder shows first, which is quite confusing and leads one to think of data loss. Instead we should display a spinner for feedback. Only when there really is no contact, show that message.

### PR DESCRIPTION
**Pull request by irgendwie**
fixes #24 
fixes #72

cc @Henni

### CODE REVIEW

**Comment by Henni** [comment]
@irgendwie https://github.com/blog/1506-closing-issues-via-pull-requests

**Comment by irgendwie** [comment]
Review pls @Henni

**Comment by Henni** [comment]
- [x] Only show no-search-result message if search is not empty.    94c3b34
- [x] Update uid if no contact in group.     db091e4
- [x] Load first contact on initial load.   5778c3b

@irgendwie on initial load a contact is chosen, but not necessarily the first one. (Maybe you are choosing the first by uid!?)

**Comment by irgendwie** [comment]
@Henni Changed to `fullName();` 411155bc549bb8521309f3c0c2b558c807ffade7
Can get merged now.

**Pull request merged**
