### PR TITLE
Groups from categories in vcards

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@Henni loading of the group via url does not yet fully work

### CODE REVIEW

**Comment by Henni** [comment]
@DeepDiver1975 should be fixed now

**Comment by Henni** [comment]
The last commit fixes the regression that clicking on a contact changes the gid.

**Comment by DeepDiver1975** [comment]
nice! :+1:

**Comment by DeepDiver1975** [comment]
there is one error I'm observing:

````
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: group in groups, Duplicate key:

**Comment by DeepDiver1975** [comment]
rebased

**Comment by DeepDiver1975** [comment]
fixes #38

**Comment by DeepDiver1975** [comment]
@jancborchardt please review

**Comment by Henni** [comment]
Highlighting of the selected group doesn't work on page load.
It should be probably based on `$routeParams`.

**Comment by DeepDiver1975** [comment]
> It should be probably based on $routeParams.

basically I need to set the selectedGroup and selectedContactId on url change as well

**Comment by DeepDiver1975** [comment]
> Highlighting of the selected group doesn't work on page load.

fixed

**Comment by jancborchardt** [comment]
HTML looks good, only the `templates/group.html` having addressBook stuff in it doesn’t fully make sense.

**Comment by DeepDiver1975** [comment]
> HTML looks good, only the templates/group.html having addressBook stuff in it doesn’t fully make sense to me.

I have no idea where this addressbook is coming from

**Comment by Henni** [comment]
Renaming addressBook to group in the following lines should fix it:
* https://github.com/owncloud/contactsrework/pull/39/files#diff-79868353fc5092cb3178673ff3e343b6R8
* https://github.com/owncloud/contactsrework/pull/39/files#diff-ec8984ffaad5cfbb8c86b4b263d7e399R1

**Comment by DeepDiver1975** [comment]
@jancborchardt fixed - I also pushed some changes to have a better empty view experience - not yet done - will work on this in a follow up pr

**Comment by jancborchardt** [comment]
Cool, let’s get this in and work on additional things in future PRs. :+1:

**Pull request merged**
