### PR TITLE
Added option to close details and automatically close on successful delete

### PR DESCRIPTION
**Pull request by Henni**
This PR adds an `X` to the details view to close it.
Additionally the details view is closed automatically when the contact was successfully deleted.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
works :+1: 

but does that make sense? @jancborchardt

**Comment by jancborchardt** [comment]
This is obsoleted by the move to the other layout #23, right?

**Comment by jancborchardt** [comment]
@Henni FYI I’m closing this, see my above comment. :)

**Comment by Henni** [comment]
@jancborchardt :+1:

**Pull request closed without merging**
