### PR TITLE
Added search functionality.

### PR DESCRIPTION
**Pull request by irgendwie**
Adds #49.
@jancborchardt

### CODE REVIEW

**Comment by jancborchardt** [comment]
NICE! Already works pretty well. Just some things, sorted by most important first:
- [x] When there is no result, there should be an empty state, with the icon-search and a message below – just copy that from the Mail app.
- [x] Changing the group using the navigation on the left should reset the search.
- [x] Can pressing enter select that result, that is open the first contact?
- [x] Currently only the name is searched. Can that be expanded to other fields like address, and phone number?

**Comment by jancborchardt** [comment]
(I rebased btw)

**Comment by Henni** [comment]
Still stuff to do, but looks good so far.

**Comment by Henni** [comment]
???
image

**Comment by irgendwie** [comment]
Fix for last bullet point in #218.

**Comment by aspdye** [comment]
According to #49, i think we should change the milestone to 1.1 :wink: #justfordocumentation

**Pull request merged**
