### PR TITLE
fix #250

### LINKED ISSUE #250: Long url overlaps icon
image

### PR DESCRIPTION
**Pull request by skjnldsv**
Simple solution for https://github.com/owncloud/contacts/issues/250

### CODE REVIEW

**Comment by irgendwie** [comment]
Looks good! :+1:

**Comment by jancborchardt** [comment]
Good one @skjnldsv! Do you mimd if I add you to our group of ownCloud designers? https://github.com/orgs/owncloud/teams/designers

**Comment by skjnldsv** [comment]
i don't mind!

**Comment by jancborchardt** [comment]
@skjnldsv you need to send a signed contributor agreement to @karlitschek then, or with a comment here state that all your contributions are MIT licensed: https://owncloud.org/contribute/agreement/

Then @karlitschek will add you to the ownCloud organization and I can add you to the group. Meanwhile you are very welcome in our IRC channel #owncloud-design :)

**Comment by skjnldsv** [comment]
You got it! :)
[owncloud-copyright-assignment-common-signed.pdf](https://github.com/owncloud/contacts/files/184105/owncloud-copyright-assignment-common.pdf)

**Comment by karlitschek** [comment]
@skjnldsv confirmed. Thanks a lot. Please confirm the github email.

**Comment by skjnldsv** [comment]
@karlitschek The github email?

**Comment by karlitschek** [comment]
you should get an email from github that you have to confirm. but it seems that you already did :-)

**Comment by skjnldsv** [comment]
:p

**Comment by jancborchardt** [comment]
@skjnldsv welcome to ownCloud and to the design team! :)

**Comment by skjnldsv** [comment]
Thank you! :)

**Pull request merged**
