### PR TITLE
Revert "Revert "Adding addressbook select on each contact""

### PR DESCRIPTION
**Pull request by DeepDiver1975**
Reverts owncloud/contacts#76

Let me see if I can fix this ....

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@Henni @irgendwie please retest - contacts creation is fixed

@Henni what was the error on group switching? I cannot reproduce this - THX

**Comment by Henni** [comment]
The issue with groups was:
image
This issue still exists on this branch.

**Comment by DeepDiver1975** [comment]
So ctrl.contact is undefined ... I cannot reproduce this ... 

``` js
        $scope.addressBook = _.find($scope.addressBooks, function(book) {
            return book.id === ctrl.contact.addressBookId;
        });
```

**Comment by DeepDiver1975** [comment]
Aha .... happens here as well .... but Chrome is not  showing the error in the console

**Comment by DeepDiver1975** [comment]
@Henni please test - THX

**Comment by Henni** [comment]
- [x] task creation
- [x] group switching

LGTM :+1:

**Pull request merged**
