### PR TITLE
In case there is not fullName we use the company name

### LINKED ISSUE #335: Support for organization-only contacts
### Steps to reproduce
1. Import or add contact with only the organization set and name not set
2. Reload page
### Expected behaviour

Contact should be added and displayed in the contacts list
### Actual behaviour

Contact doesn't show up in the browser interface, although it is still added to the database and also available in external dav clients (tested with DavDroid)
### Server configuration

**Operating system**: Debian testing

**Web server:** Apache 2.4.18

**Database:** Postgresql 9.5

**PHP version:** 7

**ownCloud version:** 9.0

**Contacts version:** 1.1.0.0

**Updated from an older ownCloud or fresh install:** fresh install

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - calendar: true
  - contacts: 1.1.0.0
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - gallery: 14.5.0
  - mail: 0.4.1
  - news: 8.1.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - activity
  - comments
  - encryption
  - external
  - federation
  - files_external
  - firstrunwizard
  - systemtags
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/var\/lib\/owncloud\/data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "updatechecker": false,
        "theme": "",
        "maintenance": false,
        "loglevel": 2,
        "log_type": "syslog",
        "mail_smtpmode": "sendmail",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_from_address": "owncloud",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "asset-pipeline.enabled": false
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Chromium 49.0.2623.108

**Operating system:** Debian unstable

**CardDAV-clients:** Browser interface
#### Web server error log

```
[03/Apr/2016:11:26:50 +0200] "GET / HTTP/2" 200 956 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:51 +0200] "GET /index.php/core/js/oc.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 678 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:52 +0200] "POST / HTTP/2" 302 1456 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /index.php/apps/files/ HTTP/2" 200 681 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/gallery/css/slideshow.css?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 496 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/gallery/css/gallerybutton.css?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 495 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files/css/files.css?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 497 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files/css/upload.css?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 496 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files/css/mobile.css?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 495 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files/css/detailsView.css?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 495 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files_trashbin/css/trash.css?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 495 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /index.php/core/js/oc.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 678 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/gallery/js/vendor/bigshot/bigshot-compressed.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 513 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/gallery/js/vendor/dompurify/src/purify.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 511 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/gallery/js/galleryutility.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 511 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/gallery/js/galleryfileaction.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 511 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/gallery/js/slideshow.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 511 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/gallery/js/slideshowcontrols.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 511 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/gallery/js/slideshowzoomablepreview.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 511 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/gallery/js/gallerybutton.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 509 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files/js/app.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 511 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files/js/newfilemenu.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 511 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files/js/file-upload.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 511 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files/js/jquery-visibility.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 510 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files/js/fileinfomodel.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 509 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files/js/filesummary.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 511 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files/js/breadcrumb.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 511 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files/js/filelist.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 513 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files/js/search.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 511 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files/js/favoritesfilelist.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 510 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files/js/tagsplugin.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 511 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files/js/favoritesplugin.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 510 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files/js/detailfileinfoview.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 509 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files/js/detailtabview.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 509 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files/js/mainfileinfodetailview.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 511 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files/js/detailsview.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 511 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files/js/fileactions.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 511 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files/js/fileactionsmenu.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 510 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files/js/files.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 511 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files/js/keyboardshortcuts.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 511 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files/js/navigation.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 510 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files_sharing/js/app.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 511 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files_sharing/js/sharedfilelist.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 511 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files_trashbin/l10n/de_DE.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 509 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files_trashbin/js/app.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 510 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files_trashbin/js/filelist.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 511 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files_sharing/js/share.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 511 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files_sharing/js/sharetabview.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 509 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files_texteditor/l10n/de_DE.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 509 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files_texteditor/js/editor.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 511 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files_texteditor/js/vendor/ace/src-noconflict/ace.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 109205 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files_versions/l10n/de_DE.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 509 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files_versions/js/versionmodel.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 509 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files_versions/js/versioncollection.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 509 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files_versions/js/versionstabview.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 511 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files_versions/js/filesplugin.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 509 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files_sharing/css/sharetabview.css?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 495 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files_texteditor/css/DroidSansMono/stylesheet.css?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 495 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files_texteditor/css/style.css?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 496 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:53 +0200] "GET /apps/files_texteditor/css/mobile.css?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 494 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:54 +0200] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/2" 200 728 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:54 +0200] "GET /index.php/apps/gallery/config?extramediatypes=1 HTTP/2" 200 625 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:54 +0200] "PROPFIND /remote.php/webdav/ HTTP/2" 207 689 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:54 +0200] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/2" 200 690 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:58 +0200] "GET /index.php/apps/contacts/ HTTP/2" 200 664 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:58 +0200] "GET /index.php/core/js/oc.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 678 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:58 +0200] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/2" 200 728 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:58 +0200] "GET /remote.php/dav/addressbooks HTTP/2" 200 683 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:58 +0200] "PROPFIND /remote.php/dav/addressbooks HTTP/2" 207 865 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:58 +0200] "PROPFIND /remote.php/dav/principals/users/**USERNAME**/ HTTP/2" 207 865 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:59 +0200] "PROPFIND /remote.php/dav/addressbooks/users/**USERNAME**/ HTTP/2" 207 866 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:59 +0200] "PROPFIND /remote.php/dav/addressbooks/users/**USERNAME**/default/ HTTP/2" 207 866 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:59 +0200] "PROPFIND /remote.php/dav/addressbooks/users/**USERNAME**/ HTTP/2" 207 865 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:26:59 +0200] "REPORT /remote.php/dav/addressbooks/users/**USERNAME**/default/ HTTP/2" 207 663 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:27:17 +0200] "PUT /remote.php/dav/addressbooks/users/**USERNAME**/default/592429ce-8a45-444d-aebb-c162c2a2372d.vcf HTTP/2" 201 677 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:27:20 +0200] "PUT /remote.php/dav/addressbooks/users/**USERNAME**/default/592429ce-8a45-444d-aebb-c162c2a2372d.vcf HTTP/2" 204 677 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:27:28 +0200] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/2" 200 728 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:27:28 +0200] "GET /index.php/apps/contacts/ HTTP/2" 200 664 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:27:29 +0200] "GET /index.php/core/js/oc.js?v=571b7006ad023019b3d72f3f402aec0b HTTP/2" 200 678 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:27:29 +0200] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/2" 200 728 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:27:29 +0200] "GET /remote.php/dav/addressbooks HTTP/2" 200 683 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:27:29 +0200] "PROPFIND /remote.php/dav/addressbooks HTTP/2" 207 865 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:27:29 +0200] "PROPFIND /remote.php/dav/principals/users/**USERNAME**/ HTTP/2" 207 865 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:27:29 +0200] "PROPFIND /remote.php/dav/addressbooks/users/**USERNAME**/ HTTP/2" 207 866 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:27:29 +0200] "PROPFIND /remote.php/dav/addressbooks/users/**USERNAME**/default/ HTTP/2" 207 866 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:27:29 +0200] "PROPFIND /remote.php/dav/addressbooks/users/**USERNAME**/ HTTP/2" 207 865 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
[03/Apr/2016:11:27:29 +0200] "REPORT /remote.php/dav/addressbooks/users/**USERNAME**/default/ HTTP/2" 207 663 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36" HTTP/2
```
#### ownCloud log (data/owncloud.log)

```
-
```
#### Browser log

```
Failed to parse SourceMap: https://***URL***/apps/contacts/js/vendor/angular-cache/dist/angular-cache.js.map
```

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #335

### CODE REVIEW

**Comment by irgendwie** [comment]
As the name is left empty, contacts with only a company end up being on the top. :-1:

**Comment by DeepDiver1975** [comment]
> As the name is left empty, contacts with only a company end up being on the top. :-1:

Ah - you mean the sort order ....

**Comment by DeepDiver1975** [comment]
@irgendwie addressed

**Comment by irgendwie** [comment]
LGTM :+1:

(sorry for the weird explanation of the issue :see_no_evil:)

**Comment by skjnldsv** [comment]
Perfect!

**Pull request merged**
