### PR TITLE
Enable/Disable addressbooks

### LINKED ISSUE #406: Addressbook visibility not switchable anymore
### Steps to reproduce
1. go to contacts app
2. open the configuration gear
3. realize there is no visibility switcher in front of the addressbooks anymore
### Expected behaviour

the sivibility switcher is a great way to organize a lot of addressbooks
AND
to check if the import function is importing to the right addressbook (atm this can only be done through a third party like thunderbird or davdroid, cause the "import to" function is missing too)
### Actual behaviour

Tell us what happens instead

no toggle switch, no "import to"
### Server configuration

**Operating system**:
ubuntu 14.04 64bit

**Web server:**
apache 2.4

**Database:**
mysql

**PHP version:**
php7

**ownCloud version:** (see ownCloud admin page)
9.0.2

**Contacts version:** (see ownCloud apps page)
1.2.0.0

**Updated from an older ownCloud or fresh install:**
updates from 9.0.1

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.1
  - comments: 0.2
  - contacts: 1.2.0.0
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - music: 0.3.11
  - news: 8.7.3
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - notes
  - ownnote
  - tasks
  - user_external
  - user_ldap

```

**The content of config/config.php:**

```
too sensitive for such a ticket
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration

**Browser:**
firefox 46

**Operating system:**
ubuntu 16.04
#### Web server error log

```
gui related problem - son no error log here
```
#### ownCloud log (data/owncloud.log)

```
gui related problem - son no error log here
```
#### Browser log

``````
gui related problem - son no error log here```
``````

### PR DESCRIPTION
**Pull request by skjnldsv**
- Add show/hide button on addressbook list
- Add more action and popup for the addressbook list
- Fix some css
- Fix delete icon hiding/removal if only one book left

capture d ecran_2016-05-10_08-35-52

fix #406

### CODE REVIEW

**Comment by skjnldsv** [comment]
Should we wait for #216?
Because right now I think we have to edit the dav client to get the `enabled` prop from addressbook

**Comment by aspdye** [comment]
Same as here ⚠️: https://github.com/owncloud/calendar/issues/489

cc @jancborchardt

**Comment by skjnldsv** [comment]
@aspdye Has this been decided?
What shall we do concerning the menu orientation in case of not enough space? Like on my screenshot above?

**Comment by aspdye** [comment]
Decided by @jancborchardt in the case above 😁 ...let's wait for a statement of him or one of the @owncloud/designers guys 😉

**Comment by skjnldsv** [comment]
I'm in too :)
I also think this is a better way of display a dropdown menu. There was a discussion about the big empty space at the end of the file page: owncloud/core#24235

@jancborchardt said we shouldn't use bottom-to-top menus, but I don't really see myself adding a 300px empty space at the end of the settings for the dropdown! :/

**Comment by davie2000** [comment]
Please add possibility to choose in which addressbook you will import contacts then. TiA!

**Comment by wopl** [comment]
Is there a solution enabling/disabling adressbooks visibility or select dedicated addressbook for import?
I am running owncloud 9.1.0 stable.

**Comment by Jather90** [comment]
please readd the possibility to enable adressbooks! at the moment you can add adressbooks and add contacts to that adressbook. you can even download/sync/whatever the 2nd, 3rd,... addressbook and see all contacts within that adressboks, but you have no chance to edit the contacts through the contacts app.

**Pull request closed without merging**
