### PR TITLE
Debounce updates

### PR DESCRIPTION
**Pull request by Henni**
This PR limits updates to twice a second.

Currently the input itself is debounced. We might move this to service later on, so that the changes propagate through the client, but not to the server.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
- [ ] on change of email there is never an update triggered

**Comment by DeepDiver1975** [comment]
- [ ] (unrelated to this pr) right sidebar content only changes if clicking on the name

**Comment by Henni** [comment]
> on change of email there is never an update triggered

this isn't implemented yet, but isn't part of this PR

> right sidebar content only changes if clicking on the name

what do you mean by this?

**Comment by DeepDiver1975** [comment]
> what do you mean by this?

https://github.com/owncloud/contactsrework/pull/19#issuecomment-182913877 :wink:

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
