### PR TITLE
small ui fixes

### PR DESCRIPTION
**Pull request by tcitworld**
Just a few ui fixes.

| Before | After |
| --- | --- |
| contacts-1-before | contacts-1-fixed |

### CODE REVIEW

**Comment by jancborchardt** [comment]
The input fields should all line up. :) @tcitworld can you fix phone and mail (and check the others) so they all line up with the address fields?

**Comment by irgendwie** [comment]
Tried to completely rework the contact details css while minimizing the hard-coded pixel...
Please review with care! :eyeglasses: 

2016-08-29-211717_330x874

Edit: Without the whitespace changes https://github.com/owncloud/contacts/pull/480/files?w=1

@jancborchardt

**Comment by irgendwie** [comment]
Changed the design of the contacts add button to look more like the mail app.

**Before:**
2016-08-29-213932_258x133
**Afterwards:**
2016-08-29-213913_255x142

**Comment by Henni** [comment]
Please fix the indentation.
Based on the [Coding Guidelines](https://doc.owncloud.org/server/9.1/developer_manual/general/codingguidelines.html#coding) we should keep the tab indentation.

**Comment by irgendwie** [comment]
@Henni should now be correctly tabified (the css file)

**Comment by irgendwie** [comment]
Last "fix" for today - make use of CSS3 Multiple Columns to split the details into two columns if screen width is bigger than 1450px (https://www.w3.org/TR/css3-multicol/)

**Comment by phsc84** [comment]
@irgendwie 
Pull Request #411 will be obsolete with your latest changes, correct? And the issue #354 will be resolved?

**Comment by irgendwie** [comment]
@phsc correct
Wasn't directly planned when I took over the PR :smile:

**Comment by skjnldsv** [comment]
@irgendwie merge this pr and we'll see later how to rewrite my previous pr for two columns flow style! ;)

Thanks! Looking great!

**Comment by skjnldsv** [comment]
LGTMN :+1: :+1:

**Pull request merged**
