### PR TITLE
Updated color filter to use the core function

### LINKED ISSUE #300: Invisible contacts letter avatar
### Expected behaviour

Contact list with different colors.
### Actual behaviour

Some contacts avatars are invisible. Selecting the list make the letter appears.

capture

Also, those contact edit page looks like this:

### Server configuration

**Operating system**: Debian

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.6

**ownCloud version:** 9.0.0

**Contacts version:** 1.1.0.0

**Updated from an older ownCloud or fresh install:** From 8.2.3

**Signing status (ownCloud 9.0 and above):** Got extra files errors after upgrade, deleted each files afterward.

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.0
  - comments: 0.2
  - contacts: true
  - dav: 0.1.5
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_locking: true
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - files_videoviewer
  - galleryplus
  - pdflintview
  - updater
  - user_external
  - user_ldap
  - user_webdavauth
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc26ab9bf921",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "domain.com"
        ],
        "datadirectory": "\/var\/www\/domain.com\/data",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud_db",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "forcessl": true,
__ MAIL INFO REMOVED__,
        "forceSSLforSubdomains": true,
        "trashbin_retention_obligation": "auto"
    }
}

```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** Nope

### PR DESCRIPTION
**Pull request by skjnldsv**
All in the title! :)
After the merging of https://github.com/owncloud/core/pull/23768, we should now use the core function:
`input.toHsl()`

Fixes #300 #337 and ref #306.

cc @IwishIcanFLighT @ionum @bohni @macmeck please test with the core function.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Will this work with 9.0.0 as well?

**Comment by skjnldsv** [comment]
It will only work with the updated placeholder generator from core, soooo it depends if they backlog it in 9.0 or not.

**Comment by bohni** [comment]
Hi, works for me. Thanks!
Edit:
I just replaced this one line (without updating core)
`var hash = input.toHsl();`

I'm running 9.0.0 (stable)

Edit2:
Hm, should have read the whole thing... input.toHsl() gives me different colors for my contacts. No contact gets a white background anymore.
But I don't know if this gives me trouble on other circumstances...

**Comment by bohni** [comment]
OK, little update
I now 
1) replaced `core/js/placeholder.js`completly with the raw file from https://raw.githubusercontent.com/owncloud/core/28571e6361eeb60ff241f8d8cc6a9a7e7fcdd318/core/js/placeholder.js
2) changed `contacts/js/public/script.js` lines 1584ff to

```
angular.module('contactsApp')
.filter('contactColor', function() {
        return function(input) {
                var hsl = input.toHsl();
                return 'hsl('+hsl[0]+', '+hsl[1]+'%, '+hsl[2]+'%)';
        };
});
```

I hope these are the right changes to do.
They work for me on 9.0.0 (stable)

Thanks!

**Comment by skjnldsv** [comment]
Perfect!

**Comment by DeepDiver1975** [comment]
as I was expecting - this is no working on a plain oc9

:-1:

**Comment by bohni** [comment]
@DeepDiver1975 It is working, as I wrote in my first comment. But you can't be sure, that there are no side effects.

**Comment by DeepDiver1975** [comment]
It is not working if you use a plain 9.0.0 as relased 4 weeks back because toHsl() simply does not exist.

**Comment by skjnldsv** [comment]
Deep is right, you need the last placeholder.js update.
Should we plan this for 2.0 then ?

**Comment by DeepDiver1975** [comment]
> Should we plan this for 2.0 then ?

does not really help - I want contacts to operate on a plain 9.0.0.

We need to add a fallback in case toHsl is not provided by core

**Comment by skjnldsv** [comment]
And you're perfectly right! 
The last 9.0 update from core doesn't even include my first color generator update. I don't exactly get how the roadmap is defined. We should get back to the same old function placeholder.js is using (since this is what is shipper with 9.0.x) and when core will be upgraded with my last color generator, we should add those two lines in this and keep the old one just in case.

This should allow retro-compatibility and should not make this package heavier by adding another color generator. What do you think?

**Comment by skjnldsv** [comment]
This should do the trick, and we would have the same colors than core (like @jancborchardt wanted in the first place)

```
if(typeof input.toHsl === 'function') {
    var hsl = input.toHsl();
    return 'hsl('+hsl[0]+', '+hsl[1]+'%, '+hsl[2]+'%)';
} else {
    var hash = input.substring(0, 4),
        maxRange = parseInt('ffff', 16),
        hue = parseInt(hash, 16) / maxRange * 256;
    return 'hsl(' + hue + ', 90%, 65%)';
};
```

**Comment by bohni** [comment]
@skjnldsv 
if you use `var hash = input.substring(0, 4),` instead of your solution in #300 (`var hash = input.toLowerCase().replace(/[^0-9a-f]+/g, '');`) all contacts will get the same color, if the UID starts with the same timestamp as the one I showed in #300 (`20131217T100925.ac9f58a2cd@example.com`)

**Comment by skjnldsv** [comment]
Yeah, I forgot a md5 :)

**Comment by bohni** [comment]
@DeepDiver1975 @skjnldsv 
I just downloaded and extracted 
- owncloud-9.0.0.tar.bz2 and copied the file `core/js/placeholder.js` to my running 9.0.0 instance
- contacts.tar.gz (1.1.0.0  from https://apps.owncloud.com/content/show.php/Contacts?content=168708) and replaced my changed js/public/script.js  on my running 9.0.0 instance

This leaded to my contacts background getting white again.

Then I changed line 1609 from
`var hash = input.split('-').join('');`
to
`var hash = input.toHsl();`
and my contacts backgorund became colored again

The diff between the extracted owncloud.tar and my instance shows:

```
$ diff -r oc owncloud-9
Only in oc/apps: calendar
Only in oc/apps: contacts
Only in oc/config: config.php
Only in oc/config: config.php.orig
```

So the change is working on plain 9.0.0

Edit: Maybe that the colors are not as randomized as with the complete change

**Comment by DeepDiver1975** [comment]
> So the change is working on plain 9.0.0

only because you patched placeholder.js - which is wrong

**Comment by DeepDiver1975** [comment]
> This should do the trick, and we would have the same colors than core (like @jancborchardt wanted in the first place)

@skjnldsv exactly what we should do! THX

**Comment by bohni** [comment]
@DeepDiver1975
I wrote, that I've undone the changes and the diff shows no difference. BUT

@DeepDiver1975  @skjnldsv 

Sorry guys. My fault. Cache or something fooled me. I used Shift-F5 to reload and colors are shown. I again shift-f5 reloaded the page and colors are gone.

**Comment by skjnldsv** [comment]
No pb :)

**Comment by skjnldsv** [comment]
Rebased and ready to merge.
@DeepDiver1975 compatibility is ok now.

Test procedure:
1. replace /core/js/placeholder.js with https://github.com/owncloud/core/blob/stable9/core/js/placeholder.js and check if you get the old ugly colours
2. now replace with https://github.com/owncloud/core/blob/master/core/js/placeholder.js and check if you get the clean "pastel" colours

**Comment by skjnldsv** [comment]
@jancborchardt could you take a look?

cc @bohni @IwishIcanFLighT @ionum @macmeck @criegerde please review following this comment https://github.com/owncloud/contacts/pull/345#issuecomment-207238351

**Comment by ghost** [comment]
Results as shown attached:

core: 
core
master:
master

**Comment by jancborchardt** [comment]
@criegerde @skjnldsv so it results in different colors? Shouldn’t they be the same? The algorithm shout definitely spit out the same color for the same value put in.

**Comment by ghost** [comment]
yes, it results in different colors.

**Comment by skjnldsv** [comment]
@criegerde no there is a problem, the first one should have terrible colors like this: 
screen
And with the new generator:
screen2

Did you applied my commit?

@jancborchardt No, this is normal, the last core update (9.0) does not include the new generator, so we're including the old color gen from core inside contacts. But we also added an alternative to be ready when core will have the last generator. Like so, we always have a matching color between core and contacts, regardless of the core version and whatever color generator the user has installed. :)

**Comment by ghost** [comment]
@skjnldsv yes, i did:
1. replace /core/js/placeholder.js with https://github.com/owncloud/core/blob/stable9/core/js/placeholder.js  **<= called core**
2. now replace with https://github.com/owncloud/core/blob/master/core/js/placeholder.js **<= called master**

**Comment by skjnldsv** [comment]
And what about the code in contacts?

**Comment by ghost** [comment]
what do you mean exactely?

**Comment by skjnldsv** [comment]
in contacts/js/public/script.js, search the code `filter('contactColor'`

And replace the whole section by this: https://github.com/owncloud/contacts/blob/use-core-colors-generator/js/filters/contactColor_filter.js
(the old function should be visible here: https://github.com/owncloud/contacts/blob/8fc233da68b2e8884d0097bddfb2ca9d87177679/js/filters/contactColor_filter.js)

**Comment by ghost** [comment]
apologize, i forgot this step.
but unfortunately the colors are still different 


positiv: the empty/white/blank letter-Icon changed to a colored one - the name of this contact is also readable

**Comment by skjnldsv** [comment]
Yeah, the colors are supposed to be different, that's normal :)

Thank you for your feedback! :+1:

**Comment by ghost** [comment]
ok, so it works fine for me!
i checked another ownc9.0.1-instance - same positiv results with clean pastel colors.
thank you!

**Comment by bohni** [comment]
Hello,

here my results:
bugfix-result

left side: old core
right side: new core

top: old contacts
center: contacts with fix from #300 
bottom: new contacts

Bohni

**Comment by skjnldsv** [comment]
So to be clear the bottom line is with this code?
https://github.com/owncloud/contacts/blob/use-core-colors-generator/js/filters/contactColor_filter.js

(This is confusing enough with all those colors, I want to be sure :p )

**Comment by bohni** [comment]
> So to be clear the bottom line is with this code?

Yes, with "new contacts" I meant your new code your link points to

**Comment by skjnldsv** [comment]
Perfect!

**Comment by skjnldsv** [comment]
@DeepDiver1975 could you do a last check? :)

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
