### PR TITLE
remove unnecessary background for non-existent profile image

### PR DESCRIPTION
**Pull request by jancborchardt**
It’s not necessary and just alludes at the possibility that photo upload is possible. Which it isn’t yet.

### CODE REVIEW

**Comment by tomneedham** [comment]
With this PR:
screen shot 2016-03-07 at 15 20 10
without: 
screen shot 2016-03-07 at 15 20 46
... in Safari on OSX

**Comment by tomneedham** [comment]
Trying to work out where that border is coming from

**Comment by tomneedham** [comment]
... Not sure. Works in Firefox but Chrome/Safari I seem to see a 1px border on the `img` tag but it doesnt actually show in the inspector

**Comment by DeepDiver1975** [comment]
Should we simply hide the logo element in case there is no photo?

@jancborchardt

**Comment by jancborchardt** [comment]
@tomneedham yeah, I was confused too. No idea where it’s coming from.

@DeepDiver1975 right, probably best choice. I added a commit to absolutely position the name so layout isn’t broken when the img is hidden. You can go for it and implement it in this PR.

**Comment by jancborchardt** [comment]
(And rebased)

**Comment by DeepDiver1975** [comment]
> Should we simply hide the logo element in case there is no photo?

done

**Comment by jancborchardt** [comment]
Thanks!

**Pull request merged**
