### PR TITLE
Adding detailed name field with all structured elements including syn…

### PR DESCRIPTION
**Pull request by DeepDiver1975**
…c N to FN

@Henni @jancborchardt @irgendwie @z000ao8q @skjnldsv

### CODE REVIEW

**Comment by irgendwie** [comment]
- Delete icon should be placed behind the last field and not under it :-1:
  2016-06-16-095439_364x276_scrot

The rest looks good! :+1:
@DeepDiver1975

**Comment by DeepDiver1975** [comment]
@irgendwie fixed - thx for testing

**Comment by irgendwie** [comment]
LGTM :+1:

**Comment by jancborchardt** [comment]
Noice! :+1:

**Comment by skjnldsv** [comment]
:+1:

**Pull request merged**
