### PR TITLE
Contacts now supports OC10.1

### PR DESCRIPTION
**Pull request by Julian1998**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
.travis.yml needs some love - it fails on e.g. php 5.6 - see https://travis-ci.org/owncloud/contacts/jobs/346358058#L842

**Comment by DeepDiver1975** [comment]
> it fails on e.g. php 5.6

which is expected since core master is 7.1+ only

**Review by DeepDiver1975 — CHANGES_REQUESTED** [review]
travis needs adjustments

**Comment by Julian1998** [comment]
@DeepDiver1975 Alright! But I will do a new PR for travis - just merge that one pls

**Pull request merged**
