### PR TITLE
Don't use wellknown if not needed

### LINKED ISSUE #41: Do not use .well-known/carddav url
For me there is a 404 request to the .well-known/carddav url in the network log:
`http://localhost/.well-known/carddav`

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #41

@nickvergessen @Henni

### CODE REVIEW

**Comment by Henni** [comment]
Looks good to me. Still works and there is no 404 anymore.

**Comment by DeepDiver1975** [comment]
rebased

**Comment by nickvergessen** [comment]
For me it still queries the well-known, because the actual lib patch is missing

**Comment by nickvergessen** [comment]
But then again, the thing only makes a get request, which returns
> This is the WebDAV interface. It can only be accessed by WebDAV clients such as the ownCloud desktop sync client.

So maybe we should just kill that get call completly...

**Comment by DeepDiver1975** [comment]
> But then again, the thing only makes a get request, which returns

grrr - where did it go?

**Comment by DeepDiver1975** [comment]
> For me it still queries the well-known, because the actual lib patch is missing

fixed - please test again - thx

**Comment by DeepDiver1975** [comment]
@nickvergessen THX

**Comment by DeepDiver1975** [comment]
rebased again

**Comment by irgendwie** [comment]
LGTM :+1:

**Pull request merged**
