### PR TITLE
Group field is now a select2 field

### PR DESCRIPTION
**Pull request by DeepDiver1975**
bildschirmfoto von 2016-03-04 14-24-37

@jancborchardt some styling is welcome - as soon as too many groups are in the list the width is exploding

bildschirmfoto von 2016-03-04 14-25-32

### CODE REVIEW

**Comment by tomneedham** [comment]
screen shot 2016-03-04 at 13 29 58
screen shot 2016-03-04 at 13 29 47
... on safari

**Comment by jancborchardt** [comment]
Dayum, I styled select2 for the tags app … maybe I only put it in the styles there. :O

**Comment by DeepDiver1975** [comment]
> Dayum, I styled select2 for the tags app … maybe I only put it in the styles there. :O

any update on this? THX

**Comment by jancborchardt** [comment]
@DeepDiver1975 ah right. Working on it.

**Comment by jancborchardt** [comment]
Done and rebased.

@DeepDiver1975 »All contacts« should not show up in that list as it’s not a real group. Every contact belongs to all contacts and can not be removed from it, so it’s not necessary to show, just confusing.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 »All contacts« should not show up in that list as it’s not a real group. Every contact belongs to all contacts and can not be removed from it, so it’s not necessary to show, just confusing.

done

**Comment by Henni** [comment]
still initally looks like this:
image

**Comment by DeepDiver1975** [comment]
@Henni fixed - THX

**Comment by jancborchardt** [comment]
There is still an empty entry, as well as »All contacts« in the list.

**Comment by DeepDiver1975** [comment]
If 'all contacts' was selected before the fix it is now stored.
Please retest with a new contact

**Comment by jancborchardt** [comment]
Creating new contact – same issue still.

Also, when I add the field »Groups«, it’s not automatically focused, unlike the other fields.

**Comment by DeepDiver1975** [comment]
> Also, when I add the field »Groups«, it’s not automatically focused, unlike the other fields.

fixed

cannot reproduce the other issue

**Comment by jancborchardt** [comment]
Rebase please, there are conflicts.

**Comment by jancborchardt** [comment]
(Fixed some more select2 CSS issues)

**Comment by jancborchardt** [comment]
Rebased, let’s get this in, we can fix details later: :+1:

**Comment by irgendwie** [comment]
LGTM :+1:

**Pull request merged**
