### PR TITLE
Hide delete function for last email, phone and address field

### LINKED ISSUE #167: Hide delete function for last email, phone and address field
When there is only one field for email, phone, or address, the delete function should be hidden. Just as you can not remove the name, it makes more sense to permanently have them there for structure, even when not filled in.

### PR DESCRIPTION
**Pull request by skjnldsv**
Hide the delete button when there's only one field left for address, mails and phone, fix #167

### CODE REVIEW

**Comment by jancborchardt** [comment]
Good stuff! Works nicely :+1:

**Comment by skjnldsv** [comment]
This doesn't prevent the backend function tho, only the frontend by hiding the delete button.
Not that big of a deal. :)

**Comment by Henni** [comment]
We might want to still show this icon. But instead of deleting the input it should just clear it.

**Comment by jancborchardt** [comment]
Then we should only show it when the field is focused. Because otherwise it again clutters the view.

**Pull request merged**
