### PR TITLE
This is the new contacts app

### PR DESCRIPTION
**Pull request by enoch85**
cc @DeepDiver1975

### CODE REVIEW

**Comment by aspdye** [comment]
:+1:

**Comment by Henni** [comment]
contatcs

**Comment by enoch85** [comment]
@Henni Fixed!

EDIT: Sorry was a little bit to fast there...

**Comment by Henni** [comment]
@enoch85 please squash
Then :+1:

**Comment by enoch85** [comment]
@Henni Don't know how to squash, sorry. Just made the changes online.

**Comment by Henni** [comment]
@enoch85 Would you mind opening a new PR?

**Comment by enoch85** [comment]
Sure

**Pull request closed without merging**
