### PR TITLE
Fix loading broken vcards

### LINKED ISSUE #311: Some characters make contacts load forever
Some characters (like 0x0c) make contacts load forever (spinning wheel).
The same contacts were working in 8.2.2, after upgrade to 9.0.0 (and later to 9.0.1 beta), contacts of one user stopped working - I've managed to export them using seamonkey and pinned down one of the broken ones. Except that, there are still some I can't even export and some of these are broken too.
Best I got after fixing the 0x0c is that I reimport the working ones (962/1024) to another user and they display (with broken diacritics etc. but that might be my export problem)

[example.vcf.txt](https://github.com/owncloud/contacts/files/193120/example.vcf.txt)
### Steps to reproduce
1. import user with 0x0c in description (example vcf attached)
2. user displays
3. reload page - spinning wheel forever
### Expected behaviour

User displayed correctly
### Actual behaviour

Loading forever
### Server configuration

**Operating system**: Debian jessie

**Web server:** Apache

**Database:** Mysql

**PHP version:** 5.6.17

**ownCloud version:** (see ownCloud admin page) 9.0.1 beta

**Contacts version:** (see ownCloud apps page) 1.1.0.0

**Updated from an older ownCloud or fresh install:** upgraded from 8.2.2

**Signing status (ownCloud 9.0 and above):** enabled, no errors
### Logs

nothing showing up when loading forever

### PR DESCRIPTION
**Pull request by DeepDiver1975**
Mainly fixes #311

### CODE REVIEW

**Comment by skjnldsv** [comment]
Great! 👍

**Comment by pbek** [comment]
Thanks a lot, can't wait to test it! :)

**Comment by DeepDiver1975** [comment]
Grab the latest release from here - happy testing

**Comment by pbek** [comment]
I just updated to v1.2.0.0 and although the "loading" graphic disappears after some time still no contacts are found. :disappointed:

**Comment by DeepDiver1975** [comment]
Please open a new issue and provide as much Information as possible

**Pull request merged**
