### PR TITLE
added documentation, website, bugs, repository

### PR DESCRIPTION
**Pull request by DeepDiver1975**
according to https://doc.owncloud.org/server/9.0/developer_manual/app/info.html

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by jancborchardt** [comment]
Looks good :+1: 

Btw, why is the category `<category>other</category>`? Shouldn’t it be something like »Social«, or from the appstore categories Tools or Productivity?

**Comment by DeepDiver1975** [comment]
> Btw, why is the category <category>other</category>? Shouldn’t it be something like »Social«, or from the appstore categories Tools or Productivity?

It is absolutely of zero meaning - kill it or leave it - no difference

**Comment by DeepDiver1975** [comment]
lol - there are two entries for category in this file :see_no_evil:

**Comment by jancborchardt** [comment]
@DeepDiver1975 can you update the branch or merge it? It seems fine.

**Pull request merged**
