### PR TITLE
Add classes to the details items

### PR DESCRIPTION
**Pull request by Henni**
@jancborchardt might still be interesting even though you said you don't need it at the moment.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@jancborchardt you still need this?

**Comment by jancborchardt** [comment]
Yup, I would still say it could be useful for future styling. :+1: 

@Henni can you resolve the conflicts?

**Comment by DeepDiver1975** [comment]
> can you resolve the conflicts?

on it

**Comment by DeepDiver1975** [comment]
rebased :+1:

**Pull request merged**
