### PR TITLE
386 - Rename Addressbooks

### PR DESCRIPTION
**Pull request by william-weber**
* move addressbook actions into popover menu
* add ability to rename an addressbook

References #386 

Can anyone provide details on how the "disable" functionality should behave? Is it still necessary?

### CODE REVIEW

**Comment by william-weber** [comment]
Would you like me to add tests around my changes?

**Comment by DeepDiver1975** [comment]
> Would you like me to add tests around my changes?

that would be awesome - THX

**Review by DeepDiver1975 — APPROVED** [review]
Once unit test are added this way go in 👍

**Comment by DeepDiver1975** [comment]
> Would you like me to add tests around my changes?

@c-lark any update? I'd like to release a new version and it would be awesome to get this in. THX

**Comment by william-weber** [comment]
Apologies, this one got away from me. Should be good to go now. 👍

**Pull request merged**
