### PR TITLE
Fix missing REV field update

### LINKED ISSUE #494: OC9.0.3/Contacts 1.3.1.0 - REV field not updated when contact details are edited
## Expected behavior

When contact details are edited using the ownCloud GUI the `REV` field should be updated with the current time-stamp. (See description of REV field on https://en.wikipedia.org/wiki/VCard#Properties)
## Current behavior

When contact details are edited using the ownCloud GUI the `REV` field is not updated with the current time-stamp. It looks like the time-stamp is kept from the time the record was created.
## Steps to reproduce
1. Create a contact record using the ownCloud GUI and enter some details like a phone number.
2. Export the address book and check the vcf record of the currently created contact record. 
   It shows e.g. `REV:2016-01-11T19:32:06+00:00`
3. Edit the previously created contact record using the ownCloud GUI by e.g. modifying the phone number.
4. Export the address book again and check the vcf record of the currently edited contact record. 
   It still shows the same time-stamp, e.g. `REV:2016-01-11T19:32:06+00:00`
#### Server Configuration

OS: Linux 3.2.81
Web server: Apache2 2.4.23
Database: MariaDB 5.5.46
PHP version: 5.6.23
ownCloud version: 9.0.3
Contacts app version: 1.3.1.0
#### Client Configuration

Browser: Firefox 48.0.1
Operating system: Windows 7

### PR DESCRIPTION
**Pull request by irgendwie**
fixes #494 

@j-ed @DeepDiver1975 review pls

### CODE REVIEW

**Comment by j-ed** [comment]
Are there any specific requirements to test this patch?
I've downloaded today's contacts-master version, installed it in my ownCloud 9.0.4 environment,
applied the patch manually and restarted the web server. Unfortunately no contacts are shown
at all afterwards. Instead the following messages were logged:

```
"message":"Could not find resource file \"\/owncloud\/apps2\/contacts\/js\/vendor\/angular-route\/angular-route.js
"message":"Could not find resource file \"\/owncloud\/apps2\/contacts\/js\/vendor\/angular-uuid4\/angular-uuid4.js
"message":"Could not find resource file \"\/owncloud\/apps2\/contacts\/js\/vendor\/angular-cache\/dist\/angular-cache.js
"message":"Could not find resource file \"\/owncloud\/apps2\/contacts\/js\/vendor\/angular-sanitize\/angular-sanitize.js
"message":"Could not find resource file \"\/owncloud\/apps2\/contacts\/js\/vendor\/ui-select\/dist\/select.js\""
"message":"Could not find resource file \"\/owncloud\/apps2\/contacts\/js\/vendor\/vcard\/src\/vcard.js\"",
"message":"Could not find resource file \"\/owncloud\/apps2\/contacts\/js\/public\/script.js
"message":"Could not find resource file \"\/owncloud\/apps2\/contacts\/js\/vendor\/angular-bootstrap\/ui-bootstrap.min.js
"message":"Could not find resource file \"\/owncloud\/apps2\/contacts\/js\/vendor\/angular-bootstrap\/ui-bootstrap-tpls.min.js
"message":"Could not find resource file \"\/owncloud\/apps2\/contacts\/js\/vendor\/jquery-timepicker\/jquery.ui.timepicker.js
```

**Comment by DeepDiver1975** [comment]
looks good - not yet tested :+1:

**Comment by irgendwie** [comment]
@j-ed If you want to test this patch, i recommend doing this in a separate test installation of ownCloud/Nextcloud!
When directly using the git repository instead of a packed release, you have to build the app before you use it, in order to pull dependencies, etc:
https://github.com/owncloud/contacts#building-the-app
Edit: Otherwise the errors in your reply occur!

Thanks for your quick reply! :blush:

**Comment by skjnldsv** [comment]
Nice! :+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by j-ed** [comment]
Thank you @irgendwie for fixing this issue. Now changes of contact records are recognized again and are synchronized with my mobile phone.

**Pull request merged**
