### PR TITLE
Gui switch FN to N in Contact-Details

### PR DESCRIPTION
**Pull request by Rello**
as the automated FN splitting for First & Last Name is not working, the input field should be split into 2 separate ones.
They update the N:[0] and N:[1] directly

_...its my first Pull-Try. thank you for your patience :-)_

### CODE REVIEW

**Comment by z000ao8q** [comment]
0a7d93b

**Comment by DeepDiver1975** [comment]
N is not first name and last name - see https://tools.ietf.org/html/rfc6350#section-6.2.2

**Comment by Rello** [comment]
sorry - I updated the typo in the first Post.
N is an array with 
N:[0] = Last
N:[1] = First

...and others. but I think to go for the workaround Last and First are the most important ones.
Currently it does not work at all (only updating FD and not N) together with the sync clients as iOS as they rely on N

**Comment by DeepDiver1975** [comment]
What happens to N:[2+] of existing vcards while editing?
Dataloss is not accepable.

**Comment by Rello** [comment]
they are untouched because the specific index is used in the setter in contact_model.js
`val[0] = value;`

if feels like a workaround until someone has a better idea. but currently the whole N\* is ignored completely when editing via the GUI.
As only the FN is updated in the GUI, you make changes which don´t reach e.g. iOS or Mac OS Calender, as the main field (n*) remains on the old content

with the change at least first & last can be edited again in GUI - better than none at all

**Comment by Rello** [comment]
existing contact:
screen shot 2016-05-31 at 22 01 52

new contact/empty input Form
screen shot 2016-05-31 at 22 02 49

alternatively they could be merged into one line also

I changed it locally on my install and it looks fine.
any other suggestion on where we go from here?

An other idea would be to look at the section where the current FN input is processed and to look at derivation rules to get the N out of this.
But as the Display Name (FN) can have any input - and the N is a strict given structure - I think N->FN makes more sense compared to FN->N

**Comment by skjnldsv** [comment]
I don't like the Idea of multiple inputs! Can't you automatic split the input into two value? Like android? :)

**Comment by DeepDiver1975** [comment]
Splitting fn to N is not easy. Different cultures have different ways to split. The android code which does the magic is hugh - i will link the code later.

**Comment by skjnldsv** [comment]
https://android.googlesource.com/platform/frameworks/opt/vcard/+/master/java/com/android/vcard/VCardBuilder.java ?

**Comment by DeepDiver1975** [comment]
https://github.com/android/platform_packages_providers_contactsprovider/blob/master/src/com/android/providers/contacts/NameSplitter.java

**Comment by skjnldsv** [comment]
Much better! :D

**Comment by phsc84** [comment]
If you would implement it like this https://github.com/owncloud/contacts/issues/324#issuecomment-207950261, the algorithm to split the names would not necessarily need to be as complex as the android code, because the user still had the possibility to correct wrongly splitted names.
Furthermore the automatic splitting could be disabled, if the N fields were already filled. That way, the risk to overwrite existing values would be zero.

**Comment by jancborchardt** [comment]
Regarding the layout: Let’s please put the input fields for first and last name next to each other, not one below the other. That just looks weird. Since the first name has variable length, we should do that via Javascript just like we do for the Organization before the Title field. :)

**Comment by DeepDiver1975** [comment]
I'm closing this for now - we have added a separate N field for now - #437

**Pull request closed without merging**
