### PR TITLE
Add CSRF token to each request

### PR DESCRIPTION
**Pull request by LukasReschke**
Big hack. But I have no idea about AngularJS :speak_no_evil:

Required once https://github.com/owncloud/core/pull/22424 is in …

@Henni Any idea how to solve this cleaner? All hijacking permitted :wink:

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/calendar-rework/blob/master/js/config/config.js#L28

**Comment by LukasReschke** [comment]
I think `httpProvider` just applies to the `$http` service of AngularJS: https://docs.angularjs.org/api/ng/service/$http

Since the library does not use `$http` it won't have any effect. That's also why https://github.com/owncloud/calendar-rework/pull/218 is there. Then again, I'm far away from being a AngularJS expert. At least it didn't work before. :hear_no_evil:

**Comment by DeepDiver1975** [comment]
needs rebase ....

**Comment by DeepDiver1975** [comment]
fine by me :+1:

**Comment by DeepDiver1975** [comment]
oh . wait dav.js is generated ...
let me fix this

**Comment by DeepDiver1975** [comment]
here we go https://github.com/owncloud/contactsrework/pull/43

**Pull request merged**
