### PR TITLE
vCard Import

### PR DESCRIPTION
**Pull request by Henni**
Basic import functionality.
Currently the import functionality is in the settings on the bottom left.
It still has to be restyled and probably moved.

### CODE REVIEW

**Comment by tomneedham** [comment]
Drag and drop import? ;)

**Comment by Henni** [comment]
@tomneedham sure. In the future ;)
In my opinion we should offer a button to make this feature discoverable, and _additionally_ allow drag and drop.

**Comment by tomneedham** [comment]
Sounds good - will test in a few minutes

**Comment by tomneedham** [comment]
I imported a vcard with about 20 contacts in and it resulted in one contact being created with all of the contacts details inside the name of the first contact in the file.

**Comment by irgendwie** [comment]
A single contact works as expected, but not a *.vcf with many contact in it.
Maybe we should iterate over `BEGIN:VCARD` and `END:VCARD` in the imported file.

**Comment by Henni** [comment]
A simple split over `END:VCARD` might fix this.
@irgendwie do you want to take over?

**Comment by irgendwie** [comment]
@Henni I think this issue isn't that easy :disappointed: 
The old contacts app had different formats for the import function:
https://github.com/owncloudarchive/contacts/tree/master/formats

Maybe we should think of a way to use them!

**Comment by Henni** [comment]
@irgendwie new commit

**Comment by irgendwie** [comment]
Nice work! :+1: VCard import should be enough for the next version.
For the styling, why not do it like the old contacts app?

settingspane

**Pull request merged**
