### PR TITLE
url -> website

### LINKED ISSUE #97: Rename »URL« to »Website«
URL is much too technical, it should be called »Website«.

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #97

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@jancborchardt

**Comment by jancborchardt** [comment]
Ah, that’s where it’s done! Will add some more changes on top, just a sec.

**Comment by jancborchardt** [comment]
Done. Just some questions:
- What’s »Role«? And what’s the difference to »Title«? Title usually is tied to the organization, right?
- Why 3 kinds of Faxes? Can’t we cut one of them? Either the generic FAX one or the FAX, HOME one? They seem to be the same essentially?
- What’s »Categories«, and how is it used?

**Comment by DeepDiver1975** [comment]
> What’s »Role«? And what’s the difference to »Title«?

https://tools.ietf.org/html/rfc6350#section-6.6.1
https://tools.ietf.org/html/rfc6350#section-6.6.2

**Comment by DeepDiver1975** [comment]
> What’s »Categories«, and how is it used?

https://tools.ietf.org/html/rfc6350#section-6.7.1 - this is where we extract our groups from

**Comment by DeepDiver1975** [comment]
> Why 3 kinds of Faxes? Can’t we cut one of them? Either the generic FAX one or the FAX, HOME one? They seem to be the same essentially?

these are the types I have when generating a contact using evolution - I'm not happy either.

**Comment by jancborchardt** [comment]
@DeepDiver1975 ok. Can we remove »Role« then from our select? It’s really quite confusing.

**Comment by DeepDiver1975** [comment]
> Can we remove »Role« then from our select? It’s really quite confusing.

and not display data which was entered on another client? not really an option from my pov

**Comment by jancborchardt** [comment]
@DeepDiver1975 we can display it when it’s there, but it is confusing when we have it in our own dropdown. Where is »Role« used in Google Contacts, iOS or Android?

Also – can we then rename »Categories« to groups? Otherwise the wording will be inconsistent.

**Comment by DeepDiver1975** [comment]
> Also – can we then rename »Categories« to groups? Otherwise the wording will be inconsistent.

sure

**Comment by DeepDiver1975** [comment]
> we can display it when it’s there, but it is confusing when we have it in our own dropdown.

one day maybe :wink:

**Comment by jancborchardt** [comment]
Hehe, ok.

**Comment by DeepDiver1975** [comment]
@jancborchardt  merge?

**Comment by Henni** [comment]
:+1:

**Pull request merged**
