### PR TITLE
Fix #220 - Escaping going crazy in some fields

### LINKED ISSUE #220: Multiple escaping in addresses
### Steps to reproduce
1. Open ownCloud Contacts
2. Add new contact
3. Enter an address field (e.g. street) with commas
### Expected behaviour

The address should not break
### Actual behaviour

Any comma in an address field is escaped multiple times, so upon save (i.e. focus blur) "Main Street, 1st floor" is changed to "Main Street\, 1st floor". When the field is focused and blurred again, it changes to "Main Street\, 1st floor" and so on. There is some escaping going wild here.
### Server configuration

**Operating system**: Debian 8

**Web server:** nginx

**Database:** MySQL 5.5

**PHP version:** PHP 5.6

**ownCloud version:** 9.0.0

**Contacts version:** 1.0.0.0

**Updated from an older ownCloud or fresh install:** Updated from 8.x

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: true
  - comments: 0.2
  - contacts: true
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - news: true
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - files_pdfviewer
  - tasks
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "512fdebce061d",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/cloud....\/data",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "de",
        "defaultapp": "files",
        "knowledgebaseenabled": true,
        "enable_avatars": true,
        "allow_user_to_change_display_name": true,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "mail_domain": "cloud.....",
        "forcessl": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "trusted_domains": [
            "cloud....."
        ],
        "mail_smtpmode": "smtp",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "appcodechecker": false,
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.mandrillapp.com",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "enable_previews": false,
        "trashbin_retention_obligation": "auto"
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Chrome 48

**Operating system:** OS X 10.11

**CardDAV-clients:** iOS 9.2, OS X 10.11

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix the escaping madness in Arrays fields (like address for example...)

### CODE REVIEW

**Comment by jancborchardt** [comment]
@skjnldsv and always @mention the folks involved in the original issue (like the reporter and other community folks which had the same problem) and ask them to review the pull request. :)

So please review @nicokaiser :)

**Comment by skjnldsv** [comment]
Sure no pb.
Can you review too? :)

**Comment by Henni** [comment]
I'm not sure this is the right place for this. We might have to fix this earlier on.
Maybe in the vCard lib
cc @DeepDiver1975

**Comment by skjnldsv** [comment]
@Henni https://github.com/owncloud/contacts/issues/220#issuecomment-201909070
Yep, not quite sure, maybe the vcard lib doesn't go inside the arrays too?

**Comment by DeepDiver1975** [comment]
I guess this should really be addressed within the vcard lib

**Comment by skjnldsv** [comment]
Could you look into it?

**Comment by DeepDiver1975** [comment]
> Could you look into it?

yes - I will

**Comment by DeepDiver1975** [comment]
here is the upstream PR - https://github.com/Heymdall/vcard/pull/4

**Comment by DeepDiver1975** [comment]
closing this PR

**Pull request closed without merging**
