### PR TITLE
Fix addressbook list design, big list and/or big name

### LINKED ISSUE #517: address books no visible
From a certain number of address books in the settings, the first address books are no longer visible!

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #517

### CODE REVIEW

**Comment by irgendwie** [comment]
Delete icon is directly "under" the 3-dot icon, which if you click too fast can lead to data loss :wink: since you'd expect a menu to open when clicking the 3-dot icon.

**Comment by skjnldsv** [comment]
@irgendwie ahah yes! It happen on mobile! (https://github.com/owncloud/contacts/issues/517#issuecomment-247410847)

Two possibilities:
1. We add a little space or leave the icon at the end to prevent wrong click
2. We add a small delay to allow the user to choose wisely

**Comment by irgendwie** [comment]
Mhm... why don't we stay like the files app and open a menu in a new dialog instead?
Hovering is neat, but not really necessary, since one won't open the dialog that often imho.

2016-09-15-203450_162x250

@jancborchardt your opinion?

**Comment by skjnldsv** [comment]
Because this popup system is broken on owncloud because of the "only towards the bottom" display.
(And because I'm a lazy a*\* and clicking takes me too much effort! :D )

Edit: this?
kazam_screencast_00002

**Comment by skjnldsv** [comment]
@irgendwie Bump! :)
@jancborchardt what's your opinion on this?

**Comment by Henni** [comment]
@skjnldsv Does this work on phones and other devices without hover?

**Comment by skjnldsv** [comment]
@Henni yes, on android on chrome/stock it works fine! :)
Don't know for other os.

**Comment by DeepDiver1975** [comment]
@skjnldsv any further steps planed? THX

**Comment by skjnldsv** [comment]
@DeepDiver1975 No i wasn't planning on doing anything further! 😄 
I stopped this pr because it didn't seemed to fit what jancborchardt wanted. You can merge if you want! 😉

**Pull request closed without merging**
