### PR TITLE
Fix #279 - import button too big in some languages

### LINKED ISSUE #279: Import button overlaps settings button in german ui
In german ui the import button overlaps the settings button.

**ownCloud version:** 9.0.0
**Contacts version:** 1.1.0

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #279, overlapping of the import button in some languages.

### CODE REVIEW

**Comment by Henni** [comment]
@skjnldsv as you are a member of owncloud, feel free to create branches directly inside this repository.
This simplifies the review process and working together on PRs.

**Comment by skjnldsv** [comment]
@Henni, Thanks, but I don't want to risk and make a mess :p 
Do be faire, i'm not the greatest git user and better safe than sorry ^^

**Comment by skjnldsv** [comment]
But I will do next time, it shouldn't be that different that creating a fork on my profile! ;)

**Comment by Henni** [comment]
Better but not perfect. Maybe we should find a solution that works independent of text width, in case of languages with even longer words than German.

@owncloud/designers what do you think?
Before:
image
now:
image

**Comment by skjnldsv** [comment]
Well, there's multiple solution:
1. We set the index of the "Settings" text to always have it above the import button
2. We remove the "Settings text" when the setting section is open
3. We set a max-width on the import button.

What do you prefer?
(alternatively, we can also just move the import button, but I liked the location of it ;) )

**Comment by jancborchardt** [comment]
@skjnldsv I gotta say I like the idea of placing the import button there. However with the translation issue it’s a bit of a problem.

I would say moving the import button below the settings header in its own line might be best. Giving it full width, might also make the settings look a bit simpler.

**Comment by skjnldsv** [comment]
Closing, we need to move it into a specific menu bar inside the settings.
Waiting for more option to add (see #297)

**Pull request closed without merging**
